# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa18d4edb421b91568204a673d3954684a54bc79a3c6573f7981cb4d7b2eff2d983b2fe60e9be3a1212ac6e9b1da483d10ca1d5d734df6e15cf3e3456e16338c

test:
  secret_key_base: e9f60373d631e8d85b747f14cc143f14b17799ef5b34d8d63b50c67a310ae2d1ae522338a092427296ae14966ccbf8e797027a00b5d1f4716a01d1dd619978c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
